### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by tlbiggs** [gordonfn/datatheme-mackenzie-pmd#2]
## User Story
As a Mackenzie DMS Developer
I want an up to date readme.md
So that I can join the project easily and know how to use the repos

## Acceptance Criteria
- [x] readme files are accessible from all repos
- [x] readme files follow a standard template
- [x] readme files are up-to-date

## Notes

---
_Tesera Standard Issue Template_

**Comment by Scobel** [comment]
I'll take a look at this and see if our readme files need updated

**Comment by Scobel** [comment]
@boriscosic how do you feel about this? Is there enough here yet to create a readme or should we wait until after Release 3.2.2 is complet

**Comment by Scobel** [comment]
e9ff4d4f2600a8a6b501823ded4839974c460a20

**Comment by Scobel** [comment]
https://github.com/gordonfn/datastream-mackenzie/commit/9e7f97ab73730fabd66ecc3c7dd34cda36b78a36#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by Scobel** [comment]
Confirmed!
